apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-pacemaker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-pacemaker
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["patch", "update", "get", "list", "watch"] # Allows removing taints from nodes.
  - apiGroups: ["woehrl.net"]
    resources: ["pacemakerconfigs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-pacemaker
subjects:
  - kind: ServiceAccount
    name: pod-pacemaker
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: pod-pacemaker
  apiGroup: rbac.authorization.k8s.io
